package com.jskaleel.fte.ui.theme

import androidx.compose.ui.graphics.Color

internal val DarkGreenGray95 = Color(0xFFF0F1EC)

internal val md_theme_light_primary = Color(0xFF5455A9)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFE1DFFF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF0C0664)
internal val md_theme_light_secondary = Color(0xFF5D5C72)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFE2E0F9)
internal val md_theme_light_onSecondaryContainer = Color(0xFF1A1A2C)
internal val md_theme_light_tertiary = Color(0xFF795369)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFD8EC)
internal val md_theme_light_onTertiaryContainer = Color(0xFF2F1124)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFBFF)
internal val md_theme_light_onBackground = Color(0xFF1C1B1F)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF1C1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
internal val md_theme_light_outline = Color(0xFF777680)
internal val md_theme_light_inverseOnSurface = Color(0xFFF3EFF4)
internal val md_theme_light_inverseSurface = Color(0xFF313034)
internal val md_theme_light_inversePrimary = Color(0xFFC1C1FF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF5455A9)
internal val md_theme_light_outlineVariant = Color(0xFFC8C5D0)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFC1C1FF)
internal val md_theme_dark_onPrimary = Color(0xFF242478)
internal val md_theme_dark_primaryContainer = Color(0xFF3C3C8F)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFE1DFFF)
internal val md_theme_dark_secondary = Color(0xFFC6C4DD)
internal val md_theme_dark_onSecondary = Color(0xFF2F2F42)
internal val md_theme_dark_secondaryContainer = Color(0xFF454559)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFE2E0F9)
internal val md_theme_dark_tertiary = Color(0xFFE9B9D3)
internal val md_theme_dark_onTertiary = Color(0xFF46263A)
internal val md_theme_dark_tertiaryContainer = Color(0xFF5F3C51)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8EC)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1C1B1F)
internal val md_theme_dark_onBackground = Color(0xFFE5E1E6)
internal val md_theme_dark_surface = Color(0xFF1C1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE5E1E6)
internal val md_theme_dark_surfaceVariant = Color(0xFF47464F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5D0)
internal val md_theme_dark_outline = Color(0xFF918F9A)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
internal val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
internal val md_theme_dark_inversePrimary = Color(0xFF5455A9)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFC1C1FF)
internal val md_theme_dark_outlineVariant = Color(0xFF47464F)
internal val md_theme_dark_scrim = Color(0xFF000000)

internal val seed = Color(0xFF5455A9)